config/routes.rb
Artgallery::Application.routes.draw do
  match '/tours/tour_items', :to => "tours#tour_items"
  resources :exhibitions
  devise_for :users
  resources :tours
  resources :admin
  resources :arts
  match '/addart', :to=> 'arts#new'
  match '/manage', :to=> 'admin#manage'
  match '/editart', :to=> 'arts#edit'
  match '/tours', :to=> 'tours#index'
  match '/manage/changepass', :to=> 'admin#changepass'
  match '/manage/create', :to=> 'admin#create'



  get "home/index"

  match 'search' => 'artworks#search'

  resources :artworks

  match 'category' => 'collections#category'
  match 'artists' => 'collections#artists'
  match 'donors' => 'collections#donors'
  match 'locations' => 'collections#locations'
  
  root :to => "collections#index"
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
	def index
	end
	
	def category
		@type = params[:type]
		@value = params[:value]
		
		unless type.nil?
  		dbartworks = Artwork.filter_by(params[:type], params[:value])
		else
			redirect_to ''
		end
		
		@artworks = dbartworks.each do |art|
		  art.imglink = 'http://s3.amazonaws.com/Art_Images/' + art.filename
	  end
		
		respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @artworks }
    end
	end
	
	def artists
		@artists = Artwork.order('creator ASC').uniq_by{|h| h.creator}
	end
	
	def donors
		@donors = Artwork.order('recfrom ASC').uniq_by{|h| h.recfrom}
	end
	
	def locations
		@locations = Artwork.order('location ASC').uniq_by{|h| h.location}
	end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/artists.html.erb
<% @artists.each do |artist|%>
	<%= link_to artist.creator, category_path(:type => 'artist', :value => artist.creator), :class => "artists_link" %></br>
<%end%>

app/views/collections/category.html.erb
<h1> Artwork
<% case @type %>
<% when 'artist' %>
<%= 'by' %>
<% when 'donor' %>
<%= 'donated by' %>
<% when 'location' %>
<%= 'at' %>
<% end %>
<%= @value%>
</h1>

<% @artworks.each do |artwork| %>
<div>
<table width="75%"><tr>
<td width="40%">
<img src="<%= artwork.imglink %>", width="100%"/>
</td>
<td>
<span><%= artwork.title %></span><br/>
<span><%= artwork.creator %></span><br/>
<span><%= artwork.object %></span><br/>
<span><%= artwork.recfrom %></span><br/>
<span><%= artwork.location %></span><br/>
<p><%= artwork.description %></p>
</td>
<% end %>

app/views/collections/donors.html.erb
<% @donors.each do |donor|%>
	<%= link_to donor.recfrom, category_path(:type => 'donor', :value => donor.recfrom), :class => "donors_link" %></br>
<%end%>

app/views/collections/index.html.erb
<h1>Tufts Art Gallery</h1></br>

<% form_tag "search", :method => 'get' do %>
<table>
<tr><th>Search by</th>
  <th>Order by</th>
  <th></th></tr>
  <tr>
<td>
    <%= select_tag(:filter, options_for_select([
      ['All', 'all'],      
      ['Artist', 'creator'],
      ['Title', 'title'],
      ['Object (type)', 'object'],
      ['Location', 'location'],
      ['Description', 'description'],
      ['Donor', 'recfrom']
       ])) %>
       </td><td>
   <%= select_tag(:order, options_for_select([  
       ['Artist', 'creator'],
       ['Title', 'title'],
       ['Object (type)', 'object'],
       ['Location', 'location'],
       ['Description', 'description'],
       ['Donor', 'recfrom']
        ])) %></td>
        <td>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", :name => nil %>
    </td>
    </tr></table>
  </p>
<% end %>

<h2>View by</h2></br>
<%= link_to "Artist", artists_path%>
<%= link_to "Donor", donors_path%>
<%= link_to "Location", locations_path%>

app/views/collections/locations.html.erb
<% @locations.each do |location|%>
	<%= link_to location.location, category_path(:type => 'location', :value => location.location), :class => "locations_link" %></br>
<%end%>