config/routes.rb
Artgallery::Application.routes.draw do
  match '/tours/tour_items', :to => "tours#tour_items"
  resources :exhibitions
  devise_for :users
  resources :tours
  resources :admin
  resources :arts
  match '/addart', :to=> 'arts#new'
  match '/manage', :to=> 'admin#manage'
  match '/editart', :to=> 'arts#edit'
  match '/tours', :to=> 'tours#index'
  match '/manage/changepass', :to=> 'admin#changepass'
  match '/manage/create', :to=> 'admin#create'



  get "home/index"

  match 'search' => 'artworks#search'

  resources :artworks

  match 'category' => 'collections#category'
  match 'artists' => 'collections#artists'
  match 'donors' => 'collections#donors'
  match 'locations' => 'collections#locations'
  
  root :to => "collections#index"
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  validates_presence_of :name
  has_many :tour_items
  has_many :artwork, :through => :tour_items
end

app/controllers/tours_controller.rb
class ToursController < CmsapplicationController
  def index
    @tours = Tour.all
  end
  
  def tour_items
    @tour_item = TourItem.new
    @tours = Tour.all
    @artworks = Artwork.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def create_tour_item
    @tour_item = TourItem.new(params[:touritem])
    if @tour_item.save
      redirect_to(tours_path)
    else
      render :action => "tour_item"
    end
  end

  # GET /tours/1
  # GET /tours/1.xml
  def show
    @tour = Tour.find(params[:id])
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
    @tour = TourItem.where(:tour_id => params[:id])
    @t_name = Tour.find(params[:id]).name 
  end

  # POST /tours
  def create
    @tour = Tour.new(params[:tour])
    if @tour.save
      redirect_to(@tour, :notice => 'Tour was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /tours/1
  # PUT /tours/1.xml
  def update
    @tour = Tour.find(params[:id])
    if @tour.update_attributes(params[:tour])
      redirect_to(@tour, :notice => 'Tour was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.xml
  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    redirect_to(tours_url)
  end
  
  def sort
    order = params[:item]
    TourItems.order(order)
    render :text => order.inspect
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= semantic_form_for @tour, do |form| %>
    <% if @tour.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

            <ul>
            <% @tour.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= form.inputs do %>
        <%= form.input :name, :required => true, :wrapper_html => { :title => "Name of the Tour" } %>
        <%= form.input :desc, :required => true, :wrapper_html => { :title => "Description of the tour" } %>
    <% end %>
    
    <%= form.buttons do %>
        <%= form.commit_button :button_html => { :class => "primary" } %>
    <% end %>
<% end %>

app/views/tours/_tour_items.html.erb
<%= semantic_form_for @touritem, :url=>arts_path do |f| %>
    <% if @touritem.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@touritem.errors.count, "error") %> prohibited this artwork from being saved:</h2>

            <ul>
            <% @touritem.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= f.inputs do %>
        <%= f.input :tour_id, :required => true, :as => :select, :collection => @tours, :wrapper_html => { :title => "Tour ID" } %>
        <%= f.input :artwork_id, :required => true, :as => :select, :collection => @artworks, :wrapper_html => { :title => "Artist ID" } %>
    <% end %>
    
    <%= f.buttons do %>
        <%= f.commit_button :button_html => { :class => "primary" } %>
    <% end %>
<% end %>

app/views/tours/edit.html.erb
<% require 'aws/s3' %>

<script type="text/javascript">
	$(document).ready(function() {
		$("#list").tableDnD();
	});
</script>

<p id="notice"><%= notice %></p>

<h1>Editing Tour: "<%= @t_name %>"</h1>

<table id="list">
  <tr>
    <th>Order</th>
    <th>Title</th>
    <th>Creator</th>
	<th>Photo</th>
  </tr>

	<% AWS::S3::Base.establish_connection!(
	    :access_key_id     => 'AKIAIWNUCQ3RBDHV6BYA',
	    :secret_access_key => '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'
	  )%>
<% i = 0 %>
<% @tour.each do |item| %>
  <tr class="item" title="<%= item.artwork.description %>" id="it-<%= i += 1 %>">
	<td class="pos"><%= item.position %></td>
    <td class="title"><%= item.artwork.title %></td>
    <td class="creator"><%= item.artwork.creator %></td>
	<td class="pic"><% fname = item.artwork.filename + '.jpg'%>
	  <img src ='<%=(AWS::S3::S3Object.url_for(fname,'Art_Images'))%>' alt='[An image of the gallery piece]' width='100px' height='100px' />
	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tour', new_tour_path %>
<style type="text/css">
  div#navbar a:nth-child(4){
    background-color:#CEF6F5;
}
</style>


<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>
<style type="text/css">
  div#navbar a:nth-child(5){
    background-color:#CEF6F5;
}
</style>

app/views/tours/index.html.erb
<h1>Listing tours</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tours.each do |tour| %>
  <tr>
    <td><%= tour.name %></td>
    <td><%= link_to 'Show', tour %></td>
    <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
    <td><%= link_to 'Destroy', tour, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tour', new_tour_path %>
<%= link_to 'Add Tour Item', '/tours/tour_items' %>
<style type="text/css">
  div#navbar a:nth-child(5){
    background-color:#CEF6F5;
}
</style>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>
<style type="text/css">
  div#navbar a:nth-child(5){
    background-color:#CEF6F5;
}
</style>

app/views/tours/show.html.erb
<% require 'aws/s3' %>

<script type="text/javascript">
	alert('go');
	$('#tour_items').sortable({items:'.item', containment:'parent', axis:'y', update: function() {
	  	$.post('/tours/sort', 	'_method=put&authenticity_token=123&'+$(this).sortable('serialize'));
	}});
</script>

<p id="notice"><%= notice %></p>

<h1>Displaying Tour: "<%= @tour.name %>"</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Creator</th>
    <th>Location</th>
	<th>Photo</th>
  </tr>

	<% AWS::S3::Base.establish_connection!(
	    :access_key_id     => 'AKIAIWNUCQ3RBDHV6BYA',
	    :secret_access_key => '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'
	  )%>

<% @tour.artwork.each do |art| %>
  <tr class="item" title="<%= art.description %>">
    <td><%= art.title %></td>
    <td><%= art.creator %></td>
    <td><%= art.location %></td>
	<td>	<% fname = art.filename + '.jpg'%>
	  <img src ='<%=(AWS::S3::S3Object.url_for(fname,'Art_Images'))%>' alt='[An image of the gallery piece]' width='100px' height='100px' />
	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tour', new_tour_path %>
<style type="text/css">
  div#navbar a:nth-child(4){
    background-color:#CEF6F5;
}
</style>


<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>
<style type="text/css">
  div#navbar a:nth-child(5){
    background-color:#CEF6F5;
}
</style>

app/views/tours/tour_item.html.erb
<h2>Edit a Tour Item</h2>

<%= render "tour_items" %>

<%= link_to 'Back', tours_path %>
<style type="text/css">
  div#navbar a:nth-child(5){
    background-color:#CEF6F5;
}
</style>