config/routes.rb
Artgallery::Application.routes.draw do
  match '/tours/tour_items', :to => "tours#tour_items"
  resources :exhibitions
  devise_for :users
  resources :tours
  resources :admin
  resources :arts
  match '/addart', :to=> 'arts#new'
  match '/manage', :to=> 'admin#manage'
  match '/editart', :to=> 'arts#edit'
  match '/tours', :to=> 'tours#index'
  match '/manage/changepass', :to=> 'admin#changepass'
  match '/manage/create', :to=> 'admin#create'



  get "home/index"

  match 'search' => 'artworks#search'

  resources :artworks

  match 'category' => 'collections#category'
  match 'artists' => 'collections#artists'
  match 'donors' => 'collections#donors'
  match 'locations' => 'collections#locations'
  
  root :to => "collections#index"
end

app/controllers/arts_controller.rb
class ArtsController < CmsapplicationController
  def index
    @artwork=Artwork.new
    @artworks = Artwork.paginate(:page => params[:page], :per_page=>10)
  end

  # GET /arts/1
  def show
    @artwork = Artwork.find(params[:id])
  end

  # GET /arts/new
  def new
    @artwork = Artwork.new
  end

  # GET /arts/1/edit
  def edit
    @artwork = Artwork.find(params[:id])
  end

  # POST /arts
  def create
    @artwork = Artwork.new(params[:artwork])
    if @artwork.save
      render :action=>"show", :notice => 'Artwork was successfully created.', :id=>@artwork.id
    else
      render :action => "new"
    end
  end

  # PUT /arts/1
  def update
    @artwork = Artwork.find(params[:id])

    if @artwork.update_attributes(params[:artwork])
      redirect_to(@artwork, :notice => 'Artwork was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /artworks/1
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    redirect_to(arts_url)
  end
end

app/helpers/arts_helper.rb
module ArtsHelper
  def trimstring(str,tlen)
    if str.length>tlen
      str=str[0..tlen]
      str=str+"..."
    end
    str
  end
end

app/views/arts/_form.html.erb
<%= semantic_form_for @artwork, :url=>arts_path do |f| %>
    <% if @artwork.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

            <ul>
            <% @artwork.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= f.inputs do %>
        <%= f.input :title, :required => true, :wrapper_html => { :title => "Title of the work of art" } %>
        <%= f.input :creator, :required => true, :wrapper_html => { :title => "Name of the artist" } %>
        <%= f.input :object, :required => true, :as => :select, :collection => ["Print", "Print, Photographic", "Drawing", "Sculpture", "Painting", "Jug (Lekythos)", "Vessel", "Cloth Fragment", "Mask", "Pectoral", "Mirror, Hand (Fragment)"], :wrapper_html => { :title => "Type of the work of art" } %>
        <%= f.input :description, :required => true, :wrapper_html => { :title => "Type of the work of art" } %>
        <%= f.input :location, :required => true, :wrapper_html => { :title => "Location of the artwork" } %>
        <%= f.input :notes, :wrapper_html => { :title => "Write any notes about the artwork" } %>
        <%= f.input :onDisplay, :wrapper_html => { :title => "Check if this artwork is currently on display" } %>
        <%= f.input :thumbnail, :as => :file, :required => true, :wrapper_html => { :title => "Upload the artwork image" } %>
    <% end %>
    
    <%= f.buttons do %>
        <%= f.commit_button :button_html => { :class => "primary" } %>
    <% end %>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/arts/index.html.erb
<h1>All Artworks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Creator</th>
    <th>Object</th>
    <th>Description</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artworks.each do |artwork| %>
  <tr>
    <td title="<%= escape_javascript artwork.title %> "><%= trimstring(artwork.title,50) %></td>
    <td><%= artwork.creator %></td>
    <td><%= artwork.object %></td>
    <td title="<%= escape_javascript artwork.description %>" ><%= trimstring(artwork.description,50) %></td>
    <td><%= artwork.location %></td>
    <!--<td><%= artwork.recfrom %></td>
    <td><%= artwork.date %></td>
    <td><%= artwork.filename %></td>
    <td><%= artwork.notes %></td>
    <td><%= artwork.onDisplay %></td>
    <td><%= artwork.thumbnail %></td>
    <td><%= artwork.lat %></td>
    <td><%= artwork.lng %></td>-->
    <td><%= link_to 'Show', arts_path+"/"+artwork.id.to_s %></td>
    <td><%= link_to 'Edit', edit_art_path(artwork) %></td>
    <td><%= link_to 'Destroy', arts_path+"/"+artwork.id.to_s, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @artworks %>
<br />
<style type="text/css">
  div#navbar a:nth-child(3){
    background-color:#CEF6F5;
}
</style>

app/views/arts/new.html.erb
<h1>New artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>
<style type="text/css">
  div#navbar a:nth-child(2){
    background-color:#CEF6F5;
}
</style>

app/views/arts/show.html.erb
<%require 'aws/s3'%>
<p id="notice"><%= notice %></p>

<p>
  <b>Object:</b>
  <%= @artwork.object %>
</p>

<p>
  <b>Creater:</b>
  <%= @artwork.creator %>
</p>

<p>
  <b>Title:</b>
  <%= @artwork.title %>
</p>

<p>
  <b>Description:</b>
  <%= @artwork.description %>
</p>

<p>
  <b>Location:</b>
  <%= @artwork.location %>
</p>

<p>
  <b>Recfrom:</b>
  <%= @artwork.recfrom %>
</p>

<p>
  <b>Date:</b>
  <%= @artwork.date %>
</p>

<p>
  <b>Filename:</b>
  <%= @artwork.filename %>
</p>

<p>
  <b>Notes:</b>
  <%= @artwork.notes %>
</p>

<p>
  <b>Ondisplay:</b>
  <%= @artwork.onDisplay %>
</p>

<p>
  <b>Thumbnail:</b>
  <%= @artwork.thumbnail %>
</p>

<p>
  <b>Lat:</b>
  <%= @artwork.lat %>
</p>

<p>
  <b>Lng:</b>
  <%= @artwork.lng %>
</p>

<p>
  <b>Image:</b><br/>
  <% AWS::S3::Base.establish_connection!(
    :access_key_id     => 'AKIAIWNUCQ3RBDHV6BYA',
    :secret_access_key => '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'
  )
  if(@artwork.filename?)
    fname = @artwork.filename + '.jpg'%>
    <img src ='<%=(AWS::S3::S3Object.url_for(fname,'Art_Images'))%>' style="width:100%;" alt='[An image of the gallery piece]'/>
  <% end %>
</p>


<%= link_to 'Edit', edit_art_path(@artwork) %> |
<%= link_to 'Back', arts_path %>
<style type="text/css">
  div#navbar a:nth-child(3){
    background-color:#CEF6F5;
}
</style>