config/routes.rb
Artgallery::Application.routes.draw do
  match '/tours/tour_items', :to => "tours#tour_items"
  resources :exhibitions
  devise_for :users
  resources :tours
  resources :admin
  resources :arts
  match '/addart', :to=> 'arts#new'
  match '/manage', :to=> 'admin#manage'
  match '/editart', :to=> 'arts#edit'
  match '/tours', :to=> 'tours#index'
  match '/manage/changepass', :to=> 'admin#changepass'
  match '/manage/create', :to=> 'admin#create'



  get "home/index"

  match 'search' => 'artworks#search'

  resources :artworks

  match 'category' => 'collections#category'
  match 'artists' => 'collections#artists'
  match 'donors' => 'collections#donors'
  match 'locations' => 'collections#locations'
  
  root :to => "collections#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artgallery</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/cmsapplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'autocomplete-rails.js' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="wrapper">
      <% if user_signed_in? %>
        <div id="header">Tufts University Art Gallery Administration <%= link_to 'Logout' ,destroy_user_session_path %>  </div>
        <div id="navbar">
          <%= link_to 'Home', admin_index_path %>
          <%= link_to 'Add Art', addart_path %>
          <%= link_to 'Search Art', :arts %>
          <%= link_to 'Exhibitions', exhibitions_path %>
          <%= link_to 'Tours', tours_path %>
          <%= link_to 'Manage', manage_path %>
        </div>
        <div id="content">
        <%  end %>
        <%= yield %>
        <% if user_signed_in? %>
        </div>
      <% end %>
    </div>
  </body>
</html>